<div class="container">
	<div class="row pt-2">

		<div class="col-md-3 sticky-top">

			<ul class="list-group">
				<li class="list-group-item"><a href="/timeline" class="text-decoration-none"><i class="bi bi-house"></i> Página Inicial</a></li>
				<li class="list-group-item"><i class="bi bi-search"></i> Explorar</li>
				<li class="list-group-item"><i class="bi bi-bell"></i> Notificações</li>
				<li class="list-group-item"><i class="bi bi-envelope"></i> Mensagens</li>
				<li class="list-group-item"><i class="bi bi-file-text"></i> Listas</li>
				<li class="list-group-item"><i class="bi bi-bookmark"></i> Itens salvos</li>
				<li class="list-group-item"><i class="bi bi-patch-check"></i> Verificadas</li>
				<li class="list-group-item"><i class="bi bi-person"></i> Perfil</li>
				<li class="list-group-item"><i class="bi bi-chat-dots"></i> Mais</li>
				<li class="list-group-item"><a class="text-decoration-none" href="/sair"><i class="bi bi-x-octagon"></i> Sair</a></li>
				<li class="list-group-item">
					<button class="btn p-0" id="theme-switcher">
						<i class="bi bi-brightness-high-fill"></i> Alterar Tema
					</button>
				</li>
			</ul>

			<script>
				document.getElementById('theme-switcher').addEventListener('click', function() {
					var body = document.body;
					var currentTheme = body.getAttribute('data-bs-theme');
					var newTheme = currentTheme === 'dark' ? 'light' : 'dark';
					body.setAttribute('data-bs-theme', newTheme);
				});
			</script>

		</div>

		<div class="col-md-6 border border-bottom-0">
			<div class="row mb-2">
				<div class="col form-floating border-bottom">
					<form method="post" action="/tweet">
						<textarea class="form-control mt-3" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>

						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-success rounded-pill"><strong>Tweet</strong></button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet border-bottom">
					<div class="col">
						<p><strong><?= $tweet['nome'] ?></strong> <small><span class="text text-muted">- <?= $tweet['data'] ?></span></small></p>
						<p><?= $tweet['tweet'] ?></p>
						<?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?>
							<form>
								<div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger"><small>Remover</small></button>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>


		</div>


		<div class="col-md-3">
			
			<div class="perfil border rounded">

				<div class="perfilPainel">
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">
								<?= $this->view->info_usuario['nome'] ?>
							</span>
						</div>
					</div>

					<div class="row mb-2">
						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_tweets['total_tweet'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguindo['total_seguindo'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguidores['total_seguidores'] ?>
							</span>
						</div>

					</div>

				</div>
			</div>

			<div class="quemSeguir border rounded">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>

			<div class="dropdown">
				<a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					Dropdown link
				</a>

				<ul class="dropdown-menu">
					<li><a class="dropdown-item" href="#" onclick="changeColor('light')">Claro</a></li>
					<li><a class="dropdown-item" href="#" onclick="changeColor('medium')">Médio</a></li>
					<li><a class="dropdown-item" href="#" onclick="changeColor('dark')">Escuro</a></li>
				</ul>
			</div>

			<div class="myclass" style="height: 300px;width: 300px;"></div>

			<script>
				function changeColor(mode) {
					let color;
					if (mode === 'light') {
						color = '#fff';
					} else if (mode === 'medium') {
						color = 'grey';
					} else if (mode === 'dark') {
						color = '#000';
					}
					document.querySelector('body').style.backgroundColor = color;
				}
			</script>
		</div>



	</div>
</div>

<script>

</script>